// <auto-generated />
using System;
using EFCore_Part1_;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Part1_.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCore_Part1_.models.Department", b =>
                {
                    b.Property<int>("DepartmentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentNumber"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeSsn")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManageStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MsgStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentNumber");

                    b.HasIndex("EmployeeSsn")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Dependent", b =>
                {
                    b.Property<int>("EmployeeSsn")
                        .HasColumnType("int");

                    b.Property<string>("DependentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DependentBdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DependentId")
                        .HasColumnType("int");

                    b.Property<string>("DependentRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependentSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("EmployeeSsn", "DependentName");

                    b.HasIndex("EmployeeSsn")
                        .IsUnique();

                    b.ToTable("dependents");
                });

            modelBuilder.Entity("EFCore_Part1_.models.DeptLocations", b =>
                {
                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentLocation")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentID", "DepartmentLocation");

                    b.ToTable("deptLocations");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Employee", b =>
                {
                    b.Property<int>("EmployeeSsn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeSsn"));

                    b.Property<DateTime>("Bdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeMinit")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<double>("EmployeeSalary")
                        .HasColumnType("float");

                    b.Property<int>("SupervisorID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSsn");

                    b.HasIndex("DepartmentNumber");

                    b.HasIndex("SupervisorID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Project", b =>
                {
                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectNumber", "ProjectName");

                    b.HasIndex("DepartmentNumber");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EFCore_Part1_.models.WorksOn", b =>
                {
                    b.Property<int>("EmployeeSsn")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSsn", "ProjectNumber", "ProjectName");

                    b.HasIndex("ProjectNumber", "ProjectName");

                    b.ToTable("worksOns");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Department", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Employee", "Employee")
                        .WithOne("ManagedDepart")
                        .HasForeignKey("EFCore_Part1_.models.Department", "EmployeeSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Dependent", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Employee", "employee")
                        .WithOne("Dependent")
                        .HasForeignKey("EFCore_Part1_.models.Dependent", "EmployeeSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("EFCore_Part1_.models.DeptLocations", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Employee", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_Part1_.models.Employee", "supervisor")
                        .WithMany("supervisee")
                        .HasForeignKey("SupervisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Project", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Department", "Department")
                        .WithMany("Project")
                        .HasForeignKey("DepartmentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EFCore_Part1_.models.WorksOn", b =>
                {
                    b.HasOne("EFCore_Part1_.models.Employee", "employee")
                        .WithMany("worksOn")
                        .HasForeignKey("EmployeeSsn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore_Part1_.models.Project", "project")
                        .WithMany("WorksOn")
                        .HasForeignKey("ProjectNumber", "ProjectName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("project");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Employee", b =>
                {
                    b.Navigation("Dependent")
                        .IsRequired();

                    b.Navigation("ManagedDepart")
                        .IsRequired();

                    b.Navigation("supervisee");

                    b.Navigation("worksOn");
                });

            modelBuilder.Entity("EFCore_Part1_.models.Project", b =>
                {
                    b.Navigation("WorksOn");
                });
#pragma warning restore 612, 618
        }
    }
}
